# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usersprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user__first_name',), 'verbose_name': 'Inscrição Atleta', 'verbose_name_plural': 'Inscrições Atletas'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emailatleta',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='/static/img/perfil', verbose_name='profile picture'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
