# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import effectiveworkout.usersprofiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofiles', '0004_auto_20160415_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default=1, upload_to=effectiveworkout.usersprofiles.models.user_directory_path),
            preserve_default=False,
        ),
    ]
