# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersprofiles', '0006_auto_20160415_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user__first_name',), 'verbose_name': 'Perfil do utilizador', 'verbose_name_plural': 'Perfis de Utilizadores'},
        ),
    ]
